name: set up configuration
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  PYTHON_VERSION:  3.13.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: |
          pip install -r requirements.txt

        
        